### ISSUE TITLE
offline-plugin: runtime was installed without OfflinePlugin being added to the webpack.config.js.

### ISSUE THREAD

**Issue by anz000** [gnarr/razzle-plugin-serviceworker#15]
I followed the procedure as mentioned in the documentation. 

However, it doesn't override the service-worker I had prior to integrating razzle. Moreover, I get the following error on the console:

```
offline-plugin: runtime was installed without OfflinePlugin being added to the webpack.config.js.
```
Is this something related to offline-plugin or this razzle plugin?

How difficult is it to integrate a custom service-worker with this plugin? I wanted to use the default CRA one as that had been working well previously.

**Comment by fivethreeo** [comment]
https://github.com/NekR/offline-plugin/blob/master/docs/troubleshooting.md#offline-plugin-isnt-working-in-dev-mode

**Comment by anz000** [comment]
I built a production version and had deployed it to my server to test it out. I ran into the console message then.

**Comment by anz000** [comment]
Lied, I didn't follow the instructions properly. I had put the `razzle.config.js` file inside the `src` directory but it was supposed to go in the `root` directory. Works great. Thanks.
